language: c

env:
  global:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libudev-dev
            - gcc-4.8
      env:
        - CMAKE_FLAGS="-DCMAKE_C_COMPILER=gcc-4.8"
    - os: osx
      compiler: clang

install:
  - if [[ -e "contrib/ci/install-$TRAVIS_OS_NAME.sh" ]]; then . contrib/ci/install-$TRAVIS_OS_NAME.sh; fi

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE $CMAKE_FLAGS ..
script:
  - make
