# We need the last tag to generate a correct version string, 50 commits is not enough
git:
  depth: 500

language: cpp

env:
  global:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env:
        - INSTALLER=linux
    - os: osx
      compiler: clang
      env:
        - INSTALLER=osx
        - QT_PACKAGE=qtbase-5.7.1-x86_64-darwin-clang-static.txz

install:
  - source contrib/ci/install-$INSTALLER.sh

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE $CMAKE_FLAGS ..
script:
  - make
  - if [[ "$INSTALLER" == "osx" ]]; then cpack; fi

deploy:
  - provider: releases
    api_key:
      secure: rf2xKEN/HM5sV+QGswfSPQiXXGSRkhz4hx9szt4zBH//PcsQmrKiaphOE+whMOz5crKWjruaFbWBXkxqYGKdVlQ4xZVyAHE1CcQGjBN7ZXZh3bcjtkD4iyqlpJJ/wQBIuNn71whFp73LEQrggzigUuWs5j+cZBd3U73ZiETZ9RKaShw2DkX7FkDj7++nyDy3RFamO5SLGhr65RtCdX7tr83lqU6q6Cv6IwYK9aBVWSMcgtH0lucO/5s3l6WHCiWUJInrovvrSebh2x/0gscS5/XfZC9HvBrsqyZA3W9fA8ioAVUZUYEx7zQDCMqKquN1bhGKd0sz9EmSsE3+08gfY2ghZ6Q6fwuslxxqctTnweWlqwxGK6D2PQHznRZmYaomvkUwSK/tlCRZdzfM133pPrYdsG6A/fgY55jIhjrkBpr/wGyl1ZQImVpH/nrKIDbkiQzAqZmev3/r3UlpNkSuAFk9TbSQF2C1mHDhUqu1gDlhp4GPDGNnUndzXgkZ0DKZOe1AZDWAkmvqDEulRh2ydYJx6yWa6FTrcxRdnHe031MJNMOk2gef6DTuK+31kc3FuBh49h40TBVjsQDL+r0RS/XduMNnWy+M2dCy8Hb8+SC1WU9ViyuHJD5zYPaStfSGfBma1aGR8kd2cwgpBX6qCC2Cedh7eWt/bp7A946rwAM=
    file: TyTools-*.*
    file_glob: true
    skip_cleanup: true
    on:
      repo: Koromix/tytools
      tags: true
