# We need the last tag to generate a correct version string, 50 commits is not enough
git:
  depth: 500

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env:
        - CMAKE_BUILD_TYPE=RelWithDebInfo
    - os: osx
      compiler: clang
      env:
        - QT_VERSION=5.5.1
        - CMAKE_BUILD_TYPE=RelWithDebInfo

install:
  - contrib/ci/install-$TRAVIS_OS_NAME.sh

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

script:
  - make
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then cpack; fi

deploy:
  provider: bintray
  file: ../contrib/ci/deploy-ci-bintray.json
  user: Koromix
  key:
    secure: "pLCdSDU/CtceBXeqy8BDbOAuZwAwerMLm4SxuGRTak/j/tOt6+D03ZLQ0JzeJ2QkJ9HldalbhxV8N2dLdu4/nDZnUO4MICUpfHDo+XUjiONG0TDfZnSeQr4XGcMufZ0vXvjLKhASQlRQLAT0fdvkJ8o89fbXNr062SpxK28Yi+FVOEFQnvMFJux8gcqxMPY4FWTiZk7hSvKRgdSSBgAPLoLYWveG6DJJ3kmD604A/G8JJ3VHSVueqzBVc8bXhuBXeAZT+7SQq4ToSHMNNUBalmwbXlo4KklYDrGsJBMl8ppX7WYIx3mEK8QTXDvS8snjBcx/F8teWalPN88gLFiiExYVQzrVIKIPm3ReAaLrW46zfPrqs9SPH+x6JOYCyC4zcLqwD1hfc5yc55jtxxDwlF4YPmAA3STsFDFL+E1EnwMXhI6C+yZ5MUBcQB/A2rVssPk5Cq393JvJ9TF4v7MZB/LU8toNNzKO2YXqjutV3jbzvI0L+/CFCUPrOg9X59qS84hmTsytUtbKJRCJJL1KBvGH1oGu+wOoDDmigrEH2vMpYqDmr2/CPGpY4uhWhJ3RywYNNAx0M5BGwShJWxXTa9K4bityrc7rneayYzAU5Hv+XtJl6O3dPHuPUTpzEG4So+SDyz+crcvIPrf2Am+8r0X2KJb+MLP/Dvt2MjrIrPY="
